### ISSUE TITLE
Interesting setting!

### ISSUE THREAD

**Issue by wanggl9705** [EricLee0224/PAD#1]
1) Do you have any plans to release the paper on Arxiv?
2) Also, we noticed that MAD has only released the simulation part of the data so far, are there any plans to release the real data?

**Comment by EricLee0224** [comment]
Thanks for your interst.  

1)We would like to release the Arxiv version ASAP, the exact timing is based on the progress of the review.   

2)Of course. For now you can play on the MAD-Sim dataset, which has almost the same data format as MVTec for user-friendly experimentation. Mad-Real we will open source in time as a challenge.

**Comment by wanggl9705** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
