### ISSUE TITLE
Quantitative results on MAD-sim

### ISSUE THREAD

**Issue by coordxyz** [EricLee0224/PAD#2]
Hi, @EricLee0224 
Are the results of Table 2 in the paper evaluated on MAD-real? Since the MAD-real is still not available, could you please share the performance comparison (like Table 2 in the paper) on MAD-sim? Thanks~
![image](https://github.com/EricLee0224/PAD/assets/47654539/5445bafc-c4e9-4de0-adda-988a0494e993)
![image](https://github.com/EricLee0224/PAD/assets/47654539/c3fefb73-6056-41e4-aafd-eecbadda97dc)

**Comment by EricLee0224** [comment]
Hi coordxyz,

The results in Table 2 of the paper were evaluated on MAD-Sim. In fact the default evaluation setting for the MAD dataset is to use the MAD-Sim set, as we wish to explore the model's ability to detect object-centric multi-pose anomalies without background's influence (Of course we also provided qualitative and quantitative results in MAD-Real in other experiments.). The Real dataset is generally used to generalize the model towards real application deployments.

If there are any other questions, feel free to reach out to me!
