### ISSUE TITLE
question about the test code

### ISSUE THREAD

**Issue by 2466885875** [EricLee0224/PAD#4]
(pad) zlx@cvlab-1:~/PAD$ python auroc_test.py --obj 01Gorilla
/home/zlx/anaconda3/envs/pad/lib/python3.8/site-packages/torchvision/transforms/transforms.py:280: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
Traceback (most recent call last):
  File "auroc_test.py", line 244, in <module>
    precision, recall, thresholds = precision_recall_curve(gt_mask.flatten(), scores.flatten())
  File "/home/zlx/anaconda3/envs/pad/lib/python3.8/site-packages/sklearn/utils/_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "/home/zlx/anaconda3/envs/pad/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 952, in precision_recall_curve
    fps, tps, thresholds = _binary_clf_curve(
  File "/home/zlx/anaconda3/envs/pad/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 806, in _binary_clf_curve
    check_consistent_length(y_true, y_score, sample_weight)
  File "/home/zlx/anaconda3/envs/pad/lib/python3.8/site-packages/sklearn/utils/validation.py", line 407, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [12995584, 3913728]

**Comment by jianglh-WHU** [comment]
Hi~ I wanna confirm first if you have run all the test samples, if not, it is normal to encounter such problems.

**Comment by 2466885875** [comment]
thank you for answer my question，I realized that the reason was not enough training，my training epoch is less than the number of the test pictures.
now i have another question,Why the number of training sessions is equal to the number of images in the test set.
I know my question is a bit simple, but I really want to know the answer.
thank you for your help.




。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EricLee0224/PAD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月9日(星期四) 下午4:04
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [EricLee0224/PAD] question about the test code (Issue #4)





 
Hi~ I wanna confirm first if you have run all the test samples, if not, it is normal to encounter such problems.

**Comment by jianglh-WHU** [comment]
Hi~
Actually, after we get a 3D model by training, we input a test set of
pictures into the network, and we can get to a correct picture in the same
pose, and then we can get where the anomalies are through these two
pictures. That's why we have set that we need to run all the test pictures
to evaluate it. But you can also modify the code yourself, that's not too
difficult.
Best,
lihan

2466885875 ***@***.***> 于2023年11月9日周四 16:36写道：
